### ISSUE TITLE
gpt 4 turbo

### ISSUE THREAD

**Issue by Koningsbruggen** [silasnevstad/GPT-Extension-VSCode#4]
Is there a way to use the new GPT 4 Turbo model?

**Comment by sneaXOR** [comment]
> Is there a way to use the new GPT 4 Turbo model?

I was looking for this too, but GPT 4 isn't working for me either. It tells me that I must be on the waiting list, but that doesn't exist any more.
If you ever find another extension that allows you to do something similar to this one (i.e. simply put a prompt in vscode and get the answer on vscode) I'd love to have it!

**Comment by silasnevstad** [comment]
Apologies for the delay, just added the latest models.

**Comment by silasnevstad** [comment]
> > Is there a way to use the new GPT 4 Turbo model?
> 
> 
> 
> I was looking for this too, but GPT 4 isn't working for me either. It tells me that I must be on the waiting list, but that doesn't exist any more.
> 
> If you ever find another extension that allows you to do something similar to this one (i.e. simply put a prompt in vscode and get the answer on vscode) I'd love to have it!

OpenAI's GPT-4-Turbo will now be the default with GPT-4 and GPT-3.5-Turbo still available.
