### ISSUE TITLE
can't ask a question

### ISSUE THREAD

**Issue by josephmansur4** [silasnevstad/GPT-Extension-VSCode#5]
every time I want to ask a question, the chat gpt says that I have reached the request limit. when I open the chat history the answer chat gpt gives is "null", can you please help me?

**Comment by silasnevstad** [comment]
Sorry for the inconvenience. I'm assuming you have reached your monthly [usage limit](https://platform.openai.com/usage). I would check and try increases this; if its not that I can investigate further.
