### ISSUE TITLE
404 code?

### ISSUE THREAD

**Issue by elefthei** [silasnevstad/GPT-Extension-VSCode#6]
I am getting a 404 after "Ask GPT" and setting the API key successfully. Any ideas?

**Comment by silasnevstad** [comment]
Are you using the davinci model? 

This model has been depreciated by OpenAI. Updating the plugin now to no longer support it.

**Comment by elefthei** [comment]
No, GPT4 and GPT4o.

**Comment by silasnevstad** [comment]
The only things I can think of that would cause a 404 are if the model does not exist (which the newest version should've just fixed) or if the [API key is broken](https://help.openai.com/en/articles/6891827-error-code-404-you-must-be-a-member-of-an-organization-to-use-the-api).

I'll keep investigating but for now I would make sure the plugin is up to date and ensure that the API key works.

**Comment by a1472521** [comment]
same problem. 

I followed the instructions and setup successfully but it shows 404 error after "Ask GPT".

**Comment by silasnevstad** [comment]
Thanks for reporting this issue, I'll try my best to get to the bottom of this.

Do you know which version of VSCode you are using (Can go to Help > About to check)? And what version of the extension, as well as, the configuration (output mode, model, etc)?

**Comment by a1472521** [comment]
Vscode:
Version: 1.90.1 (user setup)
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:01:24.262Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.17763

Extension:
GPT
v0.4.4

Set API Key-> showed set API key successfully (just created and copied from open.ai and tried several times)
Change Model -> GPT-4o(default)
Change Token Limit->1000000

If there is any other information you need to know or you want me to execute something to identify the problem, please let me know. 
Thank you.

**Comment by silasnevstad** [comment]
Thank you, I'm guessing 

> Change Token Limit->1000000

is just a typo, since it caps at 128_000.

Just updated the extension. Now it uses axios (HTTPS requests) instead of the OpenAI library and has some slightly better error handling. Please update the extension and lmk if AskGPT now works or if not what it's returning.

**Comment by a1472521** [comment]
just uninstall and reinstall the extension.

it is now GPT v0.4.6

And did the setting below again:
Set API Key-> showed set API key successfully 
Change Model -> GPT-4o(default)
Change Token Limit->128000

below is the result after AskGPT 
![image](https://github.com/silasnevstad/GPT-Extension-VSCode/assets/23141791/755d59c0-b56f-4679-902a-048164702323)

**Comment by silasnevstad** [comment]
Thanks. I just added a debug mode, so please update the extension again (should be v0.4.7). Then before using AskGPT, turn on Debug mode (using `GPT: Change Debug Mode`), open the output panel (View > Output or Ctrl+Shift+U), click on the drop down menu in the upper right corner of the output panel and select the 'GPT Debug' channel. Now when you run AskGPT you should see the debug logs, please paste them in here (p.s. remove the API key from the logs).

They should look something like:
```
Request URL: https://api.openai.com/v1/chat/completions
Request headers: {
  "Content-Type": "application/json",
  "Authorization": "Bearer REMOVE-YOUR-API-KEY-HERE"
}
Request data: {
  "model": "gpt-4o",
  "messages": [
    {
      "role": "user",
      "content": ""
    }
  ]
}
```

**Comment by a1472521** [comment]
![image](https://github.com/silasnevstad/GPT-Extension-VSCode/assets/23141791/5d5871e3-f97b-4876-961f-857213ddd320)

![image](https://github.com/silasnevstad/GPT-Extension-VSCode/assets/23141791/b70f4d4d-346a-41c4-b5b5-4e81155ad4b3)

**Comment by silasnevstad** [comment]
Thank you for your patience. Very strange. Everything looks correct in the request, 404 means "Not found", but the url and headers all look right.

Can you try running: `curl https://api.openai.com/v1/models -H "Authorization: Bearer YOUR_API_KEY"` in the terminal/Command Prompt. Here you should see the gpt-4o model:
```
    {
      "id": "gpt-4o",
      "object": "model",
      "created": 1715367049,
      "owned_by": "system"
    },
```

**Comment by a1472521** [comment]
hmm... didn't see the gpt-4o model somehow.
So in order to use gpt-4o model, I have to activate the paid  gpt-4o model API first? I thought there are some daily free limited messages to use though.

{
  "object": "list",
  "data": [
    {
      "id": "whisper-1",
      "object": "model",
      "created": 1677532384,
      "owned_by": "openai-internal"
    },
    {
      "id": "dall-e-2",
      "object": "model",
      "created": 1698798177,
      "owned_by": "system"
    },
    {
      "id": "gpt-3.5-turbo-16k",
      "object": "model",
      "created": 1683758102,
      "owned_by": "openai-internal"
    },
    {
      "id": "tts-1-hd-1106",
      "object": "model",
      "created": 1699053533,
      "owned_by": "system"
    },
    {
      "id": "tts-1-hd",
      "object": "model",
      "created": 1699046015,
      "owned_by": "system"
    },
    {
      "id": "gpt-3.5-turbo-instruct-0914",
      "object": "model",
      "created": 1694122472,
      "owned_by": "system"
    },
    {
      "id": "gpt-3.5-turbo-instruct",
      "object": "model",
      "created": 1692901427,
      "owned_by": "system"
    },
    {
      "id": "text-embedding-3-small",
      "object": "model",
      "created": 1705948997,
      "owned_by": "system"
    },
    {
      "id": "tts-1",
      "object": "model",
      "created": 1681940951,
      "owned_by": "openai-internal"
    },
    {
      "id": "text-embedding-3-large",
      "object": "model",
      "created": 1705953180,
      "owned_by": "system"
    },
    {
      "id": "babbage-002",
      "object": "model",
      "created": 1692634615,
      "owned_by": "system"
    },
    {
      "id": "gpt-3.5-turbo-0125",
      "object": "model",
      "created": 1706048358,
      "owned_by": "system"
    },
    {
      "id": "tts-1-1106",
      "object": "model",
      "created": 1699053241,
      "owned_by": "system"
    },
    {
      "id": "gpt-3.5-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "dall-e-3",
      "object": "model",
      "created": 1698785189,
      "owned_by": "system"
    },
    {
      "id": "text-embedding-ada-002",
      "object": "model",
      "created": 1671217299,
      "owned_by": "openai-internal"
    },
    {
      "id": "davinci-002",
      "object": "model",
      "created": 1692634301,
      "owned_by": "system"
    },
    {
      "id": "gpt-3.5-turbo-1106",
      "object": "model",
      "created": 1698959748,
      "owned_by": "system"
    }
  ]
}

**Comment by silasnevstad** [comment]
Huh, I also thought GPT-4o was free with limits through the API but I guess not:

> After you have made a successful payment of $5 or more (usage tier 1), you'll be able to access the GPT-4, GPT-4 Turbo, and GPT-4o models via the OpenAI API.

[OpenAI article](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4-gpt-4-turbo-and-gpt-4o)

I'll add something later to error messages to make that clearer, sorry. But if you use GPT-3.5-Turbo it works?

**Comment by a1472521** [comment]
I changed to 3.5 turbo but it says I reached the limits...
is there any limit with 3.5 turbo? 
![image](https://github.com/silasnevstad/GPT-Extension-VSCode/assets/23141791/25fb56a5-a150-4ef0-88e0-3e1ee9a46037)

i.e. didn't make any single successful gpt api request yet lol

**Comment by silasnevstad** [comment]
Yes, that error message means you received a 429 error code, which means "Rate limit reached for requests" (can read more about the errors [here](https://platform.openai.com/docs/guides/error-codes/api-errors)), but that's very weird if you haven't made a single request. I believe every model has usage limits, you can check your usage/limits here [here](https://platform.openai.com/usage)

**Comment by a1472521** [comment]
I just registered this new account on open.ai today and didn't even ask anything on open.ai too so it's impossible to have any request.

![image](https://github.com/silasnevstad/GPT-Extension-VSCode/assets/23141791/0cf23dfd-c16d-41d7-9800-576b46db1a93)

Is it that I made too many 404 bad requests so the api blocked my requests for a while...?

**Comment by silasnevstad** [comment]
I wanna say I highly doubt it but ig it could be the case. You could find out for sure by creating an entirely new account and trying.

**Comment by a1472521** [comment]
very weird. I changed another api key (from other account) but it still says I reached the limits.

idk if it blocked my IP temporarily or what, but I guess I will try it later or tomorrow then.

**Comment by a1472521** [comment]
well...just tried and it is still the same somehow :(
![image](https://github.com/silasnevstad/GPT-Extension-VSCode/assets/23141791/b9b5a311-acaa-469c-839a-fd91f00392a1)

**Comment by silasnevstad** [comment]
That is very weird. The only way you can get that message though is if you reached a rate limit for requests.

You can try
```
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [{"role": "user", "content": "Test"}]
  }'
```
in the terminal/Command Prompt and see if you get the same error. So error code should be 429 with "Rate limit reached for requests" message if you reached a rate limit.

**Comment by a1472521** [comment]
I tried the above curl and the result is still the same.

It seems that the only free version is ChatGPT, the APIs aren’t (unless you have credits in your account)

The extension seems fine and I will get some credits to try it out later then. 

Thank you so much for your help!

**Comment by silasnevstad** [comment]
No problem! Thank you for making me aware of this problem and for your patience! Hope it works out :)
